# version: '3.8'

services:
  jenkins:
    build: .
    image: jenkins-docker
    container_name: jenkins-docker
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins_home:/var/jenkins_home
    restart: always
